name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - run: ./unit-tests.ss build-and-test
